/*
 * This file was generated by the Gradle 'init' task.
 *
 * This is a general purpose Gradle build.
 * Learn more about Gradle by exploring our Samples at https://docs.gradle.org/8.14.2/samples
 * This project uses @Incubating APIs which are subject to change.
 */
plugins {
    kotlin("jvm") version "2.1.21" // Kotlin version to use
    kotlin("plugin.serialization") version "2.1.21"
    application
}

kotlin {
    jvmToolchain {
        languageVersion.set(JavaLanguageVersion.of(23))
        vendor.set(JvmVendorSpec.ADOPTIUM)
    }
}

group = "fr.rtz"
version = "1.0-SNAPSHOT"

application {
    mainClass = "fr.rtz.mqtt_tester.AppKt"
}

repositories { 
    mavenCentral()
}

dependencies {
    implementation("io.vertx:vertx-mqtt:5.0.0")
    implementation("org.jetbrains.kotlinx:kotlinx-serialization-json:1.8.1")
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.10.2")
    // Logging
    implementation("io.github.oshai:kotlin-logging-jvm:7.0.3")
    implementation(libs.logback.classic)
}